# Generated by Django 2.2.14 on 2020-08-10 05:58

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCustomTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('my_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreapp.Category', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='TaggedWhatever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreapp_taggedwhatever_tagged_items', to='contenttypes.ContentType', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreapp_taggedwhatever_items', to='accreapp.MyCustomTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='accreapp.TaggedWhatever', to='accreapp.MyCustomTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='taggedfile',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreapp.File', verbose_name='File to Tag'),
        ),
    ]
