# Generated by Django 2.2.14 on 2020-08-10 08:26

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('accreapp', '0006_auto_20200810_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='taggedwhatever',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggedwhatever',
            name='tag',
        ),
        migrations.AlterField(
            model_name='file',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='MyCustomTag',
        ),
        migrations.DeleteModel(
            name='TaggedWhatever',
        ),
        migrations.AddField(
            model_name='taggedfile',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreapp.File', verbose_name='File to Tag'),
        ),
        migrations.AddField(
            model_name='taggedfile',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreapp_taggedfile_items', to='taggit.Tag'),
        ),
    ]
