# Generated by Django 2.2.14 on 2020-08-10 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreapp', '0007_auto_20200810_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedfile',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accreapp.Category', verbose_name='Tag'),
        ),
    ]
