# Generated by Django 2.2.14 on 2020-08-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreapp', '0010_auto_20200811_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggedwhatever',
            options={'verbose_name': 'Tagged File', 'verbose_name_plural': 'Tagged Files'},
        ),
        migrations.DeleteModel(
            name='TaggedFile',
        ),
    ]
