# Generated by Django 2.2.14 on 2020-08-12 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accreapp', '0011_auto_20200811_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Upload Date'),
        ),
    ]
