# Generated by Django 2.2.14 on 2020-08-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreapp', '0012_auto_20200812_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateField(blank=True, null=True, verbose_name='Date Created'),
        ),
    ]
