# Generated by Django 2.2.14 on 2020-08-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreapp', '0013_auto_20200812_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='alias',
        ),
    ]
