# Generated by Django 3.1 on 2020-08-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreapp', '0014_remove_category_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='Slug'),
        ),
    ]
