# Generated by Django 2.2.14 on 2020-08-18 07:30

from django.db import migrations
import django.db.models.deletion
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accreapp', '0015_auto_20200814_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedwhatever',
            name='tag',
            field=select2.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreapp_taggedwhatever_items', to='accreapp.Category'),
        ),
    ]
