# Generated by Django 2.2.14 on 2020-08-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreapp', '0016_auto_20200818_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='III', max_length=2, verbose_name='Code')),
                ('course', models.CharField(default='BSIS', max_length=5, verbose_name='Courses')),
                ('accre_date', models.DateField(blank=True, null=True, verbose_name='Date of Accreditation')),
            ],
        ),
    ]
