# Generated by Django 2.2.14 on 2020-08-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreapp', '0017_accredetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accredetails',
            name='level',
            field=models.CharField(default='III', max_length=3, verbose_name='Code'),
        ),
    ]
