# Generated by Django 2.2.14 on 2020-08-19 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreapp', '0018_auto_20200819_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='accre_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreapp.AccreDetails', verbose_name='Accreditation Details'),
        ),
    ]
