# Generated by Django 2.2.14 on 2020-08-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreapp', '0019_file_accre_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accredetails',
            options={'verbose_name': 'Accreditation Detail', 'verbose_name_plural': 'Accreditation Detail'},
        ),
        migrations.AddField(
            model_name='file',
            name='flag',
            field=models.BooleanField(default=0),
        ),
    ]
